# Generated by Django 3.2.9 on 2022-01-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Delivery', '0004_auto_20220104_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
